alias vim="/usr/local/Cellar/vim/7.4.1257/bin/vim"
alias vi="/usr/local/Cellar/vim/7.4.1257/bin/vim"
alias cdapp="cd /Users/annietang/api"
alias arc="slc arc"
alias start_dev_fly="NODE_ENV="dev" nodemon ~/api/server/server.js"
alias medicost_dev="nodemon ~/medicost/backend/server/server.js"
alias tma="tmux attach-session -t"
alias tmrn="tmux new -s"
alias tml="tmux list-sessions"
alias tmk="tmux kill-session -t"
alias tmarc=". ~/.tmux_arc.sh"
alias tmserv=". ~/.tmux_dev.sh"
alias tmedicost=". ~/.tmux_medicost_dev.sh"

