alias c="cd ~"
alias cd..="cd .."
alias vi="vim"
alias ls="ls -G"
alias l="ls"
#set up ssh
alias s="ssh kirk@usve77726.serverprofi24.com"
alias shadow="ssh root@192.241.196.56"

#replace me
export NVM_DIR="/Users/khadley/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

source ~/.bashrc
export MONGO_PATH=/usr/local/mongodb
export PATH=$PATH:$MONGO_PATH/bin
export PATH="/usr/local/bin:$PATH"
