alias vim="/usr/local/Cellar/vim/7.4.1941/bin/vim"
alias vi="/usr/local/Cellar/vim/7.4.1941/bin/vim"
alias arc="slc arc"
alias tma="tmux attach-session -t"
alias tmrn="tmux new -s"
alias tml="tmux list-sessions"
alias tmk="tmux kill-session -t"
alias cd..="cd .."

